### ISSUE TITLE
#include "/dev/random" 会使OJ卡死...

### ISSUE THREAD

**Issue by sqd** [593141477/bashu-onlinejudge#6]
作死试了一下我错了orz
估计/dev/zero也会是一个效果

**Comment by imcaffrey** [comment]
:+1:

**Comment by sqd** [comment]
@imcaffrey 泥怎么会出现在这里的

**Comment by imcaffrey** [comment]
@sqd 我只是偶然搜到了bashuoj。。。

**Comment by sqd** [comment]
@imcaffrey 其实主站是在这里 http://oj.bashu.com.cn/ 。。。不过好像不开放注册

**Comment by imcaffrey** [comment]
%%%

**Comment by Harry-Chen** [comment]
@z4yx 搜include urandom，第一个就是你这个repo，23333

**Comment by z4yx** [comment]
233333
