### ISSUE TITLE
发现一个逻辑上的小问题

### ISSUE THREAD

**Issue by jimmy19990** [593141477/bashu-onlinejudge#9]
Ranklist那里的AC率不应该单纯地用AC题数/总提交数 而应该是 AC题数/提交题数

这样就导致如果一个题有两次AC提交记录ranklist的AC率会下降，因为AC题数没增加，而提交次数却增加了。。。

谢谢！

**Comment by imcaffrey** [comment]
感觉好多别的OJ也是类似的设计吧。。。
